workflows:
  android-workflow:
    name: BlackDeath Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Setup
        script: |
          unzip blackdeath_project.zip
          cp -r blackdeath/* .
      - name: Packages
        script: flutter pub get
      - name: Build
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
