workflows:
  android-workflow:
    name: BlackDeath Android
    max_build_duration: 120
    environment:
      flutter: 3.27.0
    scripts:
      - name: Setup
        script: |
          unzip blackdeath_project.zip
          cp -r blackdeath_v2/. .
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
