name: blackdeath
description: BlackDeath AI Assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.0
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  url_launcher: ^6.3.0
  battery_plus: ^6.0.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  flutter_local_notifications: ^17.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
